###> 011-clamd
--- 
- name: ClamAV Daemon Server Deployment - RWI Tech.
  vars_files:
    - vars/sec_vars.yml
    - vars/deployment_vars.yml
    - vars/deployment_output_vars.yml
    - vars/aws_template_vars.yml
    - vars/instance_vars.yml
  hosts: localhost
  gather_facts: false
  tasks:
     # VPC Exists/Create
#    - name: VPC Exists
#      import_tasks:
#        file: tasks/create_vpc.yml

    # AWS bucket and/or registry storage w/access policies for project software and configurations
    # AWS storage w/access policies for project software and configurations

    - name: Instance Profile(s) loop create
      import_tasks:
        file: tasks/create_test_instance_profile.yml

    - name: Instance(s) loop create
      import_tasks: 
        file: tasks/ec2_test_instance.yml

    - name: Update deployment inventory.yml
      shell: |
        php "{{ script_path }}/update_inventory.php" "{{ groups }}"
      ignore_errors: true
      register: php_output
    - debug:
        msg: "{{ php_output }}"

- name: Run play basic ubuntu server setup
  import_playbook: configure_test_instance.yml

- name: Run play clamav daemon server
  import_playbook: deploy_clamav.yml
