###> 011-clamd
--- 
- name: ClamAV Daemon Server Deployment - RWI Tech.
  vars_files:
    - vars/sec_vars.yml
    - vars/deployment_vars.yml
    - vars/aws_template_vars.yml
    - vars/instance_vars.yml
    - vars/asg_vars.yml
  hosts: localhost
  gather_facts: false
  tasks:
     # VPC Exists/Create
#    - name: VPC Exists
#      import_tasks:
#        file: tasks/create_vpc.yml

    # Deployment record title/product_id/vpc_id
    - name: Deployment Record Create/exists
      import_tasks:
        file: tasks/deployment_record.yml

#    # New project keypair exists or create
#    - name: import new key task key_pair
#      import_tasks:
#        file: tasks/key_pair.yml

    # AWS bucket and/or registry storage w/access policies for project software and configurations
    # AWS storage w/access policies for project software and configurations
    - name: import S3 and ECR creation task
      import_tasks:
        file: tasks/create_s3_policy.yml

    - name: import S3 and ECR creation task
      import_tasks:
        file: tasks/create_s3_bucket.yml

    # Networking exists or create
    - name: Create Node communication subnet
      import_tasks:
        file: tasks/subnet.yml

    - name: Create node communication security group
      import_tasks:
        file: tasks/create_security_group.yml

    - name: Show security group sg instance_id
      ansible.builtin.debug:
        var: sg_info['group_id']

    - name: EC2 Assume Role exists/create 
      import_tasks:
        file: tasks/create_assume_role.yml

    - name: Instance Profile(s) loop create
      import_tasks:
        file: tasks/create_instance_profile.yml

    - name: Instance(s) loop create
      import_tasks: 
        file: tasks/ec2_instance.yml

    - name: Update deployment inventory.yml
      shell: |
        php "{{ script_path }}/update_inventory.php" "{{ groups }}"
      ignore_errors: true
      register: php_output
    - debug:
        msg: "{{ php_output }}"


- name: Run play basic ubuntu server setup
  import_playbook: configure_instance.yml

- name: Run play clamav daemon server
  import_playbook: deploy_clamav_daemon.yml
