    # EC2 instance access
    - name: AWS IAM Instance Profile - Create
      ansible.builtin.command: aws iam create-instance-profile
        --instance-profile-name "{{ instances[0].instance_profile }}"
      ignore_errors: true

    - name: Deployment Record Update Instance Profile
      lineinfile:
        state: present
        create: true
        path: "{{ deployment_log }}"
        regexp: 'instance_profile:'
        line: "instance_profile: {{ instances[0].instance_profile }}"

