- name: remove ufw
  become: true
  ansible.builtin.apt:
    name: ufw
    state: absent
  ignore_errors: true

- name: Iptables is installed
  become: true
  ansible.builtin.apt:
    name: iptables
    state: latest

- name: Iptables-persistent is installed
  become: true
  ansible.builtin.apt:
    name: iptables-persistent
    state: latest

- name: Iptables - Allow ssh connections
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    ctstate: NEW,ESTABLISHED,RELATED
    source: "{{ item }}"
    destination_ports:
      - "22"
      - "1523"
    jump: ACCEPT
    state: present
  ignore_errors: false
  loop:
    - "{{ ncom_net_cidr }}"
    - "{{ my_ip }}"
- name: Insure directory /etc/iptables
  become: true
  shell: |
    sudo mkdir /etc/iptables
  ignore_errors: true

- name: Insure the file exists
  become: true
  shell: |
    sudo touch -a /etc/iptables/rules.v4
  ignore_errors: true

- name: Save iptables current state
  become: true
  shell: |
    sudo iptables-save > /etc/iptables/rules.v4
  ignore_errors: true
  register: save
- debug:
    msg: "{{ save.stdout }}"
